spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_home_db?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  type-aliases-package: com.example.smart_home_web.pojo
  type-enums-package: com.example.smart_home_web.enums

server:
  port: 8080
  servlet:
    session:
      timeout: 3600s